name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pypdf pdfplumber pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile naming_ekho_unlock+deletehunweekly.py --add-data "hungarian_names.txt;."

    - name: Upload exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-exe
        path: dist/naming_ekho_unlock+deletehunweekly.exe
